const listEl     = document.getElementById("list");
const emptyEl    = document.getElementById("empty");
const statsEl    = document.getElementById("stats");
const searchEl   = document.getElementById("search");
const refreshBtn = document.getElementById("refresh");
const exportAllBtn = document.getElementById("export-all");

// ── i18n ───────────────────────────────────────────────────
// Mirrors the overlay's STRINGS table; locale is shared via chrome.storage
// under the key "vn:locale" so options follows whatever the user picked there.

const STRINGS = {
  en: {
    pageTitle:         "FrameJian · Library",
    subtitle:          "All saved notes & AI summaries",
    searchPlaceholder: "Search video titles…",
    refresh:           "Refresh",
    exportAll:         "Export all",
    statVideos:        "Videos",
    statNotes:         "Notes",
    statSummaries:     "AI summaries",
    updatedPrefix:     "Updated ",
    cardExport:        "Export",
    cardDelete:        "Delete entire video record",
    tabNotes:          "Notes",
    tabSummary:        "AI summary",
    notesEmpty:        "No notes for this video yet.",
    summaryEmpty:      "No AI summary yet. Open the video page and generate one from the AI summary tab.",
    summaryLabel:      "Generated by Gemini",
    copyAll:           "Copy",
    copied:            "Copied",
    exportSummary:     "Export",
    deleteSummary:     "Delete",
    confirmDelete:     (title) => `Delete all notes and summary for "${title}"?`,
    confirmDelSummary: "Delete this AI summary?",
    tsTitle:           "Jump to this moment in the video",
    thumbTitle:        "Open video",
    edit:              "Edit",
    delete:            "Delete",
    save:              "Save",
    cancel:            "Cancel",
    noMatch:           (q) => `No records matching "${q}".`,
    emptyTitle:        "No records yet",
    emptySub:          "Open a YouTube or Bilibili video page to start taking notes.",
    untitled:          "Untitled",
    summarySectionH:   "AI Summary",
    notesSectionH:     "Notes",
    exportMetaSource:  "Source",
    exportMetaPlatform:"Platform",
    exportMetaVideoId: "Video ID",
    exportMetaUpdated: "Updated",
    exportNoNotes:     "No notes yet.",
    exportNoSummary:   "No AI summary yet.",
    exportNoteAdded:   "added",
  },
  zh: {
    pageTitle:         "帧笺 FrameJian · 记录库",
    subtitle:          "所有保存的笔记与 AI 摘要",
    searchPlaceholder: "搜索视频标题…",
    refresh:           "刷新",
    exportAll:         "导出全部",
    statVideos:        "视频",
    statNotes:         "笔记",
    statSummaries:     "AI 摘要",
    updatedPrefix:     "更新于 ",
    cardExport:        "导出",
    cardDelete:        "删除整个视频记录",
    tabNotes:          "笔记",
    tabSummary:        "AI 摘要",
    notesEmpty:        "这个视频还没有笔记。",
    summaryEmpty:      "还没有生成 AI 摘要。请回到视频页，在 AI 摘要标签中生成。",
    summaryLabel:      "由 Gemini 生成",
    copyAll:           "复制",
    copied:            "已复制",
    exportSummary:     "导出",
    deleteSummary:     "删除",
    confirmDelete:     (title) => `确认删除「${title}」的全部笔记与摘要？`,
    confirmDelSummary: "确认删除这条 AI 摘要？",
    tsTitle:           "在视频中跳转到此处",
    thumbTitle:        "打开视频",
    edit:              "编辑",
    delete:            "删除",
    save:              "保存",
    cancel:            "取消",
    noMatch:           (q) => `没有匹配「${q}」的记录。`,
    emptyTitle:        "还没有任何记录",
    emptySub:          "打开 YouTube 或 Bilibili 视频页，开始记录你的第一条笔记。",
    untitled:          "Untitled",
    summarySectionH:   "AI 摘要",
    notesSectionH:     "笔记",
    exportMetaSource:  "来源",
    exportMetaPlatform:"平台",
    exportMetaVideoId: "视频 ID",
    exportMetaUpdated: "更新于",
    exportNoNotes:     "暂无笔记。",
    exportNoSummary:   "暂无 AI 摘要。",
    exportNoteAdded:   "记于",
  },
};

let locale = "zh";
let t = STRINGS.zh;

const applyStaticLocale = () => {
  document.documentElement.lang = locale;
  document.title = t.pageTitle;
  document.getElementById("fj-subtitle").textContent     = t.subtitle;
  document.getElementById("refresh-label").textContent   = t.refresh;
  document.getElementById("export-all-label").textContent = t.exportAll;
  document.getElementById("empty-title").textContent     = t.emptyTitle;
  document.getElementById("empty-sub").textContent       = t.emptySub;
  searchEl.placeholder = t.searchPlaceholder;
};

let allEntries = [];

const formatTime = (seconds) => {
  const total = Math.max(0, Math.floor(seconds || 0));
  const h = Math.floor(total / 3600);
  const m = Math.floor((total % 3600) / 60);
  const s = total % 60;
  const hh = h > 0 ? String(h).padStart(2, "0") + ":" : "";
  return `${hh}${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`;
};

const formatDate = (ts) => {
  if (!ts) return "";
  const d = new Date(ts);
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  const hh = String(d.getHours()).padStart(2, "0");
  const mm = String(d.getMinutes()).padStart(2, "0");
  return `${y}-${m}-${day} ${hh}:${mm}`;
};

const platformLabel = (platform) => {
  if (platform === "youtube") return "YouTube";
  if (platform === "bilibili") return "Bilibili";
  return platform || "—";
};

// Build a deep-link URL with timestamp parameter for the given platform
const linkAtTime = (payload, seconds) => {
  const t = Math.max(0, Math.floor(seconds || 0));
  if (!payload.url) return "#";
  let built = payload.url;
  if (payload.platform === "youtube") {
    try {
      const u = new URL(payload.url);
      u.searchParams.set("t", `${t}s`);
      built = u.toString();
    } catch {}
  } else if (payload.platform === "bilibili") {
    try {
      const u = new URL(payload.url);
      u.searchParams.set("t", String(t));
      built = u.toString();
    } catch {}
  }
  // Re-validate scheme — payload.url could in theory be a javascript: URL
  // that URL() accepts; only allow http(s)/mailto through.
  return safeUrl(built);
};

const exportPayload = (payload) => {
  const lines    = [];
  const title    = payload.title || t.untitled;
  const platform = platformLabel(payload.platform);
  const notes    = Array.isArray(payload.notes) ? payload.notes : [];
  const summary  = payload.summary || null;

  // Title
  lines.push(`# ${title}`);
  lines.push("");

  // Metadata block
  if (payload.url)       lines.push(`- **${t.exportMetaSource}**: <${payload.url}>`);
  if (payload.platform)  lines.push(`- **${t.exportMetaPlatform}**: ${platform}`);
  if (payload.id)        lines.push(`- **${t.exportMetaVideoId}**: \`${payload.id}\``);
  if (payload.updatedAt) lines.push(`- **${t.exportMetaUpdated}**: ${formatDate(payload.updatedAt)}`);
  lines.push("");

  // Notes section
  lines.push(`## ${t.notesSectionH} (${notes.length})`);
  lines.push("");
  if (notes.length) {
    notes.forEach((note) => {
      const tsTag   = `**[${formatTime(note.t)}]**`;
      const dateStr = note.createdAt
        ? `  \n  _${t.exportNoteAdded} ${formatDate(note.createdAt)}_`
        : "";
      // Indent body so multi-line notes stay inside the bullet
      const body = (note.text || "").split(/\r?\n/).join("\n  ");
      lines.push(`- ${tsTag} ${body}${dateStr}`);
    });
  } else {
    lines.push(`_${t.exportNoNotes}_`);
  }
  lines.push("");

  // Summary section
  lines.push(`## ${t.summarySectionH}`);
  lines.push("");
  if (summary && summary.text) {
    if (summary.updatedAt) {
      lines.push(`_${t.summaryLabel} · ${formatDate(summary.updatedAt)}_`);
      lines.push("");
    }
    lines.push(summary.text.trim());
  } else {
    lines.push(`_${t.exportNoSummary}_`);
  }
  lines.push("");

  return lines.join("\n");
};

const downloadText = (text, filename) => {
  const blob = new Blob([text], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
};

const safeFilename = (s) => (s || "notes").replace(/[^a-zA-Z0-9_一-龥-]+/g, "-").replace(/^-+|-+$/g, "");

// Icons
const ICON_DOWNLOAD = `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>`;
const ICON_TRASH    = `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="3 6 5 6 21 6"/><path d="M19 6l-1 14a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2L5 6"/><path d="M10 11v6"/><path d="M14 11v6"/><path d="M9 6V4a2 2 0 0 1 2-2h2a2 2 0 0 1 2 2v2"/></svg>`;
const ICON_PLAY     = `<svg width="22" height="22" viewBox="0 0 24 24" fill="currentColor"><polygon points="6 4 20 12 6 20 6 4"/></svg>`;

// Best-effort thumbnail URL with fallback for older payloads (pre-thumbnail era)
const thumbnailFor = (payload) => {
  if (payload.thumbnail) return payload.thumbnail;
  if (payload.platform === "youtube" && payload.id && payload.id !== "unknown") {
    return `https://i.ytimg.com/vi/${payload.id}/mqdefault.jpg`;
  }
  return "";
};

// URL values come from third-party pages (location.href, og:image), so we
// only allow safe schemes — never let `javascript:` etc. reach an href/src.
const safeUrl = (url) => {
  if (!url) return "#";
  try {
    const u = new URL(url, location.href);
    return /^(https?|mailto):$/.test(u.protocol) ? url : "#";
  } catch { return "#"; }
};

/* ── Minimal Markdown renderer ─────────────────────────────
   Supports: # h1..h6, **bold**, *italic*, `code`, ```fenced```,
             - / * / 1. lists, > blockquote, [text](url), --- hr.
   Returns sanitized HTML (input is HTML-escaped first).
   Timestamp tokens like [12:34] are left as plain text and
   converted to clickable links in a post-processing step. */

const escapeHtml = (s) => s
  .replace(/&/g, "&amp;")
  .replace(/</g, "&lt;")
  .replace(/>/g, "&gt;");

const renderInline = (s) => s
  .replace(/`([^`\n]+)`/g, "<code>$1</code>")
  .replace(/\*\*([^*\n]+)\*\*/g, "<strong>$1</strong>")
  .replace(/(^|[^\*])\*([^*\n]+)\*(?!\*)/g, "$1<em>$2</em>")
  .replace(/\[([^\]\n]+)\]\((https?:\/\/[^\s)]+)\)/g, '<a href="$2" target="_blank" rel="noreferrer">$1</a>');

const renderMarkdown = (raw) => {
  let text = escapeHtml(raw);

  // Fenced code blocks first (protect content from other transforms)
  const codeBlocks = [];
  text = text.replace(/```([a-z0-9]*)\n?([\s\S]*?)```/gi, (_, lang, code) => {
    const idx = codeBlocks.length;
    codeBlocks.push(`<pre><code>${code.replace(/\n$/, "")}</code></pre>`);
    return `\x00CB${idx}\x00`;
  });

  const lines = text.split(/\r?\n/);
  const out = [];
  let listType = null;        // "ul" | "ol" | null
  let inBlockquote = false;
  let paragraphBuf = [];

  const flushParagraph = () => {
    if (paragraphBuf.length) {
      out.push(`<p>${paragraphBuf.join("<br>")}</p>`);
      paragraphBuf = [];
    }
  };
  const closeList = () => {
    if (listType) { out.push(`</${listType}>`); listType = null; }
  };
  const closeBlockquote = () => {
    if (inBlockquote) { out.push("</blockquote>"); inBlockquote = false; }
  };

  for (const rawLine of lines) {
    const line = rawLine.trimEnd();

    if (!line.trim()) {
      flushParagraph();
      closeList();
      closeBlockquote();
      continue;
    }

    // Horizontal rule
    if (/^(?:-{3,}|\*{3,}|_{3,})$/.test(line.trim())) {
      flushParagraph();
      closeList();
      closeBlockquote();
      out.push("<hr>");
      continue;
    }

    // Heading
    const hMatch = line.match(/^(#{1,6})\s+(.*)$/);
    if (hMatch) {
      flushParagraph();
      closeList();
      closeBlockquote();
      out.push(`<h${hMatch[1].length}>${renderInline(hMatch[2].trim())}</h${hMatch[1].length}>`);
      continue;
    }

    // Blockquote
    if (line.startsWith("&gt; ") || line.startsWith("> ")) {
      flushParagraph();
      closeList();
      if (!inBlockquote) { out.push("<blockquote>"); inBlockquote = true; }
      out.push(`<p>${renderInline(line.replace(/^(&gt;|>)\s+/, ""))}</p>`);
      continue;
    }
    closeBlockquote();

    // Bullet list
    const ulMatch = line.match(/^\s*[-*+]\s+(.*)$/);
    if (ulMatch) {
      flushParagraph();
      if (listType !== "ul") { closeList(); out.push("<ul>"); listType = "ul"; }
      out.push(`<li>${renderInline(ulMatch[1])}</li>`);
      continue;
    }

    // Numbered list
    const olMatch = line.match(/^\s*\d+\.\s+(.*)$/);
    if (olMatch) {
      flushParagraph();
      if (listType !== "ol") { closeList(); out.push("<ol>"); listType = "ol"; }
      out.push(`<li>${renderInline(olMatch[1])}</li>`);
      continue;
    }

    closeList();
    paragraphBuf.push(renderInline(line));
  }
  flushParagraph();
  closeList();
  closeBlockquote();

  // Restore code blocks
  let html = out.join("\n");
  html = html.replace(/\x00CB(\d+)\x00/g, (_, idx) => codeBlocks[Number(idx)]);
  return html;
};

// Walk a rendered DOM tree, replacing [MM:SS] text patterns with timestamp links
const linkifyTimestampsIn = (root, payload) => {
  const tsRE = /\[(\d{1,2}):(\d{2})(?::(\d{2}))?\]/g;
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
    acceptNode: (n) => tsRE.test(n.nodeValue) ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_REJECT,
  });
  const targets = [];
  let cur;
  while ((cur = walker.nextNode())) targets.push(cur);

  targets.forEach((textNode) => {
    tsRE.lastIndex = 0;
    const parent = textNode.parentNode;
    const value  = textNode.nodeValue;
    const frag   = document.createDocumentFragment();
    let lastIdx  = 0;
    let m;
    while ((m = tsRE.exec(value)) !== null) {
      if (m.index > lastIdx) frag.appendChild(document.createTextNode(value.slice(lastIdx, m.index)));
      const secs = m[3] !== undefined
        ? +m[1] * 3600 + +m[2] * 60 + +m[3]
        : +m[1] * 60 + +m[2];
      const a = document.createElement("a");
      a.className   = "fj-ts-link";
      a.textContent = m[0];
      a.href        = linkAtTime(payload, secs);
      a.target      = "_blank";
      a.rel         = "noreferrer";
      frag.appendChild(a);
      lastIdx = m.index + m[0].length;
    }
    if (lastIdx < value.length) frag.appendChild(document.createTextNode(value.slice(lastIdx)));
    parent.replaceChild(frag, textNode);
  });
};

const renderStats = () => {
  const totalVideos = allEntries.length;
  const totalNotes  = allEntries.reduce((sum, e) => sum + (e.payload.notes?.length || 0), 0);
  const totalSummaries = allEntries.filter((e) => e.payload.summary && e.payload.summary.text).length;
  statsEl.innerHTML = `
    <div class="fj-stat">
      <div class="fj-stat-num"><span class="fj-stat-accent">${totalVideos}</span></div>
      <div class="fj-stat-label">${t.statVideos}</div>
    </div>
    <div class="fj-stat">
      <div class="fj-stat-num"><span class="fj-stat-accent">${totalNotes}</span></div>
      <div class="fj-stat-label">${t.statNotes}</div>
    </div>
    <div class="fj-stat">
      <div class="fj-stat-num"><span class="fj-stat-accent">${totalSummaries}</span></div>
      <div class="fj-stat-label">${t.statSummaries}</div>
    </div>
  `;
};

const renderSummaryHTML = (payload, container) => {
  const text = payload.summary?.text || "";
  container.innerHTML = renderMarkdown(text);
  linkifyTimestampsIn(container, payload);
};

const renderCard = (entry) => {
  const { key, payload } = entry;
  const notes    = Array.isArray(payload.notes) ? payload.notes : [];
  const summary  = payload.summary || null;
  const hasSummary = !!(summary && summary.text);

  const card = document.createElement("article");
  card.className = "fj-card";

  // Head — static structure only; all user data set via DOM properties below
  const head = document.createElement("div");
  head.className = "fj-card-head";
  const thumbUrl = thumbnailFor(payload);
  const sanitizedUrl = safeUrl(payload.url);
  head.innerHTML = `
    <div class="fj-card-thumb"></div>
    <div class="fj-card-meta">
      <h3 class="fj-card-title"></h3>
      <div class="fj-card-info">
        <span class="fj-platform-pill">${platformLabel(payload.platform)}</span>
        <a class="fj-card-link" target="_blank" rel="noreferrer"></a>
        <span class="fj-card-dot">·</span>
        <span class="fj-card-date">${t.updatedPrefix}${formatDate(payload.updatedAt)}</span>
      </div>
    </div>
    <div class="fj-card-actions">
      <button class="fj-ic-btn" data-action="export" title="${t.cardExport}">${ICON_DOWNLOAD}</button>
      <button class="fj-ic-btn danger" data-action="delete" title="${t.cardDelete}">${ICON_TRASH}</button>
    </div>
  `;

  // Build the thumb via DOM APIs so payload.url / thumbUrl / payload.platform
  // (third-party data) never get interpolated into raw HTML.
  const thumbBox = head.querySelector(".fj-card-thumb");
  thumbBox.dataset.platform = payload.platform || "";

  const thumbLink = document.createElement("a");
  thumbLink.className = "fj-card-thumb-link";
  thumbLink.href      = sanitizedUrl;
  thumbLink.target    = "_blank";
  thumbLink.rel       = "noreferrer";
  thumbLink.title     = t.thumbTitle;

  const renderThumbFallback = () => {
    thumbLink.textContent = "";
    const fb = document.createElement("span");
    fb.className = "fj-card-thumb-fallback";
    fb.innerHTML = ICON_PLAY; // static SVG
    thumbLink.appendChild(fb);
  };

  if (thumbUrl) {
    const img = document.createElement("img");
    img.className      = "fj-card-thumb-img";
    img.src            = thumbUrl;       // property assignment — auto-escaped
    img.alt            = "";
    img.loading        = "lazy";
    img.referrerPolicy = "no-referrer";
    img.addEventListener("error", renderThumbFallback);
    const playOverlay = document.createElement("span");
    playOverlay.className = "fj-card-thumb-play";
    playOverlay.innerHTML = ICON_PLAY;
    thumbLink.appendChild(img);
    thumbLink.appendChild(playOverlay);
  } else {
    renderThumbFallback();
  }
  thumbBox.appendChild(thumbLink);

  head.querySelector(".fj-card-title").textContent = payload.title || t.untitled;
  const linkEl = head.querySelector(".fj-card-link");
  linkEl.textContent = payload.url || "—";
  linkEl.href        = sanitizedUrl;

  head.querySelector('[data-action="export"]').addEventListener("click", () => {
    downloadText(exportPayload(payload), `${safeFilename(payload.title)}.md`);
  });

  head.querySelector('[data-action="delete"]').addEventListener("click", () => {
    if (!confirm(t.confirmDelete(payload.title || t.untitled))) return;
    chrome.storage.local.remove(key, loadAll);
  });

  card.appendChild(head);

  // Tabs
  const tabs = document.createElement("div");
  tabs.className = "fj-card-tabs";
  tabs.innerHTML = `
    <button class="fj-card-tab active" data-tab="notes">
      ${t.tabNotes} <span class="fj-tab-pill">${notes.length}</span>
    </button>
    <button class="fj-card-tab" data-tab="summary">
      ${t.tabSummary} <span class="fj-tab-pill">${hasSummary ? "✦" : "—"}</span>
    </button>
  `;
  card.appendChild(tabs);

  // Notes panel
  const notesPanel = document.createElement("div");
  notesPanel.className = "fj-card-panel notes-panel active";

  if (!notes.length) {
    notesPanel.innerHTML = `
      <div class="fj-panel-empty">
        <div class="fj-panel-empty-ic">∅</div>
        ${t.notesEmpty}
      </div>`;
  } else {
    notes.forEach((note, idx) => {
      const row = document.createElement("div");
      row.className = "fj-note-row";

      const tsLink = document.createElement("a");
      tsLink.className   = "fj-note-ts-btn";
      tsLink.textContent = formatTime(note.t);
      tsLink.href        = linkAtTime(payload, note.t);
      tsLink.target      = "_blank";
      tsLink.rel         = "noreferrer";
      tsLink.title       = t.tsTitle;

      const body = document.createElement("div");
      body.className = "fj-note-body";

      const bodyText = document.createElement("div");
      bodyText.textContent = note.text;
      body.appendChild(bodyText);

      if (note.createdAt) {
        const meta = document.createElement("div");
        meta.className = "fj-note-meta";
        meta.textContent = formatDate(note.createdAt);
        body.appendChild(meta);
      }

      const acts = document.createElement("div");
      acts.className = "fj-note-row-actions";

      const editBtn = document.createElement("button");
      editBtn.className   = "fj-mini-btn";
      editBtn.textContent = t.edit;
      editBtn.addEventListener("click", () => {
        const editor = document.createElement("textarea");
        editor.className = "fj-edit-area";
        editor.value     = note.text;
        body.innerHTML = "";
        body.appendChild(editor);

        acts.innerHTML = "";
        const saveBtn = document.createElement("button");
        saveBtn.className   = "fj-mini-btn primary";
        saveBtn.textContent = t.save;
        const cancelBtn = document.createElement("button");
        cancelBtn.className   = "fj-mini-btn";
        cancelBtn.textContent = t.cancel;

        saveBtn.addEventListener("click", () => {
          const val = editor.value.trim();
          if (!val) return;
          payload.notes[idx].text = val;
          payload.updatedAt = Date.now();
          chrome.storage.local.set({ [key]: payload }, loadAll);
        });
        cancelBtn.addEventListener("click", loadAll);

        acts.appendChild(saveBtn);
        acts.appendChild(cancelBtn);
        acts.style.opacity = 1;
        editor.focus();
      });

      const delBtn = document.createElement("button");
      delBtn.className   = "fj-mini-btn danger";
      delBtn.textContent = t.delete;
      delBtn.addEventListener("click", () => {
        payload.notes.splice(idx, 1);
        payload.updatedAt = Date.now();
        chrome.storage.local.set({ [key]: payload }, loadAll);
      });

      acts.appendChild(editBtn);
      acts.appendChild(delBtn);

      row.appendChild(tsLink);
      row.appendChild(body);
      row.appendChild(acts);
      notesPanel.appendChild(row);
    });
  }
  card.appendChild(notesPanel);

  // Summary panel
  const summaryPanel = document.createElement("div");
  summaryPanel.className = "fj-card-panel summary-panel";

  if (!hasSummary) {
    summaryPanel.innerHTML = `
      <div class="fj-panel-empty">
        <div class="fj-panel-empty-ic">✦</div>
        ${t.summaryEmpty}
      </div>`;
  } else {
    const wrap = document.createElement("div");
    wrap.className = "fj-summary-wrap";

    const bar = document.createElement("div");
    bar.className = "fj-summary-bar";
    bar.innerHTML = `
      <span class="fj-summary-label">${t.summaryLabel}</span>
      <span class="fj-summary-meta">${formatDate(summary.updatedAt)}</span>
    `;
    wrap.appendChild(bar);

    const body = document.createElement("div");
    body.className = "fj-summary-body";
    renderSummaryHTML(payload, body);
    wrap.appendChild(body);

    summaryPanel.appendChild(wrap);

    const acts = document.createElement("div");
    acts.className = "fj-summary-actions";

    const copyBtn = document.createElement("button");
    copyBtn.className   = "fj-mini-btn";
    copyBtn.textContent = t.copyAll;
    copyBtn.addEventListener("click", async () => {
      try {
        await navigator.clipboard.writeText(summary.text);
        const label = copyBtn.textContent;
        copyBtn.textContent = t.copied;
        setTimeout(() => (copyBtn.textContent = label), 1200);
      } catch {}
    });

    const exportBtn = document.createElement("button");
    exportBtn.className   = "fj-mini-btn";
    exportBtn.textContent = t.exportSummary;
    exportBtn.addEventListener("click", () => {
      const lines = [`# ${payload.title || t.untitled} — ${t.summarySectionH}`, payload.url || "", "", summary.text];
      downloadText(lines.join("\n"), `${safeFilename(payload.title)}-summary.md`);
    });

    const delSummaryBtn = document.createElement("button");
    delSummaryBtn.className   = "fj-mini-btn danger";
    delSummaryBtn.textContent = t.deleteSummary;
    delSummaryBtn.addEventListener("click", () => {
      if (!confirm(t.confirmDelSummary)) return;
      delete payload.summary;
      payload.updatedAt = Date.now();
      chrome.storage.local.set({ [key]: payload }, loadAll);
    });

    acts.appendChild(copyBtn);
    acts.appendChild(exportBtn);
    acts.appendChild(delSummaryBtn);
    summaryPanel.appendChild(acts);
  }
  card.appendChild(summaryPanel);

  // Tab switching
  tabs.querySelectorAll(".fj-card-tab").forEach((btn) => {
    btn.addEventListener("click", () => {
      const target = btn.dataset.tab;
      tabs.querySelectorAll(".fj-card-tab").forEach((b) => b.classList.toggle("active", b === btn));
      notesPanel.classList.toggle("active", target === "notes");
      summaryPanel.classList.toggle("active", target === "summary");
    });
  });

  return card;
};

const applyFilter = () => {
  const q = (searchEl.value || "").trim().toLowerCase();
  const filtered = !q
    ? allEntries
    : allEntries.filter((e) => {
        const p = e.payload;
        return (
          (p.title || "").toLowerCase().includes(q) ||
          (p.url || "").toLowerCase().includes(q) ||
          (p.id || "").toLowerCase().includes(q) ||
          (Array.isArray(p.notes) && p.notes.some((n) => (n.text || "").toLowerCase().includes(q))) ||
          (p.summary?.text || "").toLowerCase().includes(q)
        );
      });

  listEl.innerHTML = "";
  if (!filtered.length && !allEntries.length) {
    emptyEl.classList.add("visible");
    return;
  }
  emptyEl.classList.remove("visible");

  if (!filtered.length) {
    listEl.innerHTML = `<div class="fj-panel-empty" style="background: var(--fj-paper-3); border: 0.5px solid var(--fj-hair); border-radius: 14px;">
      <div class="fj-panel-empty-ic">⌕</div>
      ${t.noMatch(q)}
    </div>`;
    return;
  }

  filtered.forEach((entry) => listEl.appendChild(renderCard(entry)));
};

const loadAll = () => {
  chrome.storage.local.get(null, (items) => {
    allEntries = Object.entries(items)
      .filter(([key, payload]) => key.startsWith("vn:") && Array.isArray(payload?.notes))
      .map(([key, payload]) => ({ key, payload }))
      .sort((a, b) => (b.payload?.updatedAt || 0) - (a.payload?.updatedAt || 0));

    renderStats();
    applyFilter();
  });
};

exportAllBtn.addEventListener("click", () => {
  if (!allEntries.length) return;
  // Three blank lines between videos — each entry already starts with an H1,
  // so we avoid `---` (which the AI summary uses internally) as a separator.
  const merged = allEntries.map(({ payload }) => exportPayload(payload)).join("\n\n\n");
  downloadText(merged, "framejian-all.md");
});

refreshBtn.addEventListener("click", loadAll);
searchEl.addEventListener("input", applyFilter);

// Load locale first (shared with overlay), then render
chrome.storage.local.get(["vn:locale"], (result) => {
  locale = result["vn:locale"] === "en" ? "en" : "zh";
  t = STRINGS[locale];
  applyStaticLocale();
  loadAll();
});

// Re-render if user switches locale from the overlay while this page is open
chrome.storage.onChanged.addListener((changes, area) => {
  if (area !== "local" || !changes["vn:locale"]) return;
  const next = changes["vn:locale"].newValue === "en" ? "en" : "zh";
  if (next === locale) return;
  locale = next;
  t = STRINGS[locale];
  applyStaticLocale();
  loadAll();
});
